/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.BankRelationsBase
import io.swagger.client.model.BankRelationsBaseWithIdAndRoot
import io.swagger.client.model.CustomerAssociationBase
import io.swagger.client.model.CustomerAssociationBaseWithIdAndRoot
import io.swagger.client.model.DemographicBase
import io.swagger.client.model.DemographicBaseWithIdAndRoot
import io.swagger.client.model.ReferenceBase
import io.swagger.client.model.ReferenceBaseWithIdAndRoot
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object RegisterApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 201 : BankRelationsBaseWithIdAndRoot (Successfully registerd a bank relation)
   * 
   * @param crReferenceId Customer Reference Data Directory Entry Reference
   * @param body 
   */
  def registerCustomerReferenceDataDirectoryBankRelationship(crReferenceId: String, body: BankRelationsBase): ApiRequest[BankRelationsBaseWithIdAndRoot] =
    ApiRequest[BankRelationsBaseWithIdAndRoot](ApiMethods.POST, "https://virtserver.swaggerhub.com/BIAN/sd-customer-reference-data-management/4.0.0", "/customer-reference-data-management/customer-reference-data-directory/{cr-reference-id}/bankrelations/registration", "application/json")
      .withBody(body)
      .withPathParam("cr-reference-id", crReferenceId)
      .withSuccessResponse[BankRelationsBaseWithIdAndRoot](201)
        /**
   * 
   * 
   * Expected answers:
   *   code 201 : DemographicBaseWithIdAndRoot (Successfully registered a demographic.)
   * 
   * @param crReferenceId Customer Reference Data Directory Entry Reference
   * @param body 
   */
  def registerCustomerReferenceDataDirectoryDemographic(crReferenceId: String, body: DemographicBase): ApiRequest[DemographicBaseWithIdAndRoot] =
    ApiRequest[DemographicBaseWithIdAndRoot](ApiMethods.POST, "https://virtserver.swaggerhub.com/BIAN/sd-customer-reference-data-management/4.0.0", "/customer-reference-data-management/customer-reference-data-directory/{cr-reference-id}/demographics/registration", "application/json")
      .withBody(body)
      .withPathParam("cr-reference-id", crReferenceId)
      .withSuccessResponse[DemographicBaseWithIdAndRoot](201)
        /**
   * 
   * 
   * Expected answers:
   *   code 201 : ReferenceBaseWithIdAndRoot (Successfully registerd reference)
   * 
   * @param crReferenceId Customer Reference Data Directory Entry Reference
   * @param body 
   */
  def registerCustomerReferenceDataDirectoryEntryReference(crReferenceId: String, body: ReferenceBase): ApiRequest[ReferenceBaseWithIdAndRoot] =
    ApiRequest[ReferenceBaseWithIdAndRoot](ApiMethods.POST, "https://virtserver.swaggerhub.com/BIAN/sd-customer-reference-data-management/4.0.0", "/customer-reference-data-management/customer-reference-data-directory/{cr-reference-id}/references/registration", "application/json")
      .withBody(body)
      .withPathParam("cr-reference-id", crReferenceId)
      .withSuccessResponse[ReferenceBaseWithIdAndRoot](201)
        /**
   * Register: Customer relationships/association detail
   * 
   * Expected answers:
   *   code 201 : CustomerAssociationBaseWithIdAndRoot (Successfully registered an association)
   * 
   * @param crReferenceId Customer Reference Data Directory Entry Reference
   * @param body 
   */
  def registerCustomerReferenceDataDirectoryRelationship(crReferenceId: String, body: Option[CustomerAssociationBase] = None): ApiRequest[CustomerAssociationBaseWithIdAndRoot] =
    ApiRequest[CustomerAssociationBaseWithIdAndRoot](ApiMethods.POST, "https://virtserver.swaggerhub.com/BIAN/sd-customer-reference-data-management/4.0.0", "/customer-reference-data-management/customer-reference-data-directory/{cr-reference-id}/associations/registration", "application/json")
      .withBody(body)
      .withPathParam("cr-reference-id", crReferenceId)
      .withSuccessResponse[CustomerAssociationBaseWithIdAndRoot](201)
      

}

