/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object TerminateApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 204 :  (successful)
   * 
   * @param crReferenceId Product Instance Reference
   */
  def terminateCurrentAccountFulfillmentArrangement(crReferenceId: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/BIAN/current-account/3.0.1", "/current-account/current-account-fulfillment-arrangement/{cr-reference-id}", "application/json")
      .withPathParam("cr-reference-id", crReferenceId)
      .withSuccessResponse[Unit](204)
      

}

