/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class BankRelationsBase (
  /* `status: Provisionally Registered`   bian-reference:  CustomerRegistryEntry.RegisteredCustomer  */
  customerReference: Option[String],
  /* `status: Provisionally Registered`   bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager   general-info: relationship manager  */
  bankRelationType: Option[String],
  /* `status: Provisionally Registered`   bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager.BusinessUnit  */
  businessUnitEmployeeReference: Option[String]
) extends ApiModel


