/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ConsumerLoanDisbursementWithId (
  /* `status: Registered` bian-reference:  Loan.LoanAccount(asAccount).Identification iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E1rHgsTGEeChad0JzLk7QA_-1068889728/elements/_E1rHhcTGEeChad0JzLk7QA_-755813725) general-info: loan account number  */
  productInstanceReference: Option[String],
  /* `status: Provisionally Registered` bian-reference:  Loan.Disbursement.DisbursementOrder  */
  disbursementOrderReference: Option[String],
  /* `status: Registered` bian-reference:  LoanAgreement.TradePartyRole(asBorrower)(asRole).Player(asParty) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633) general-info: loan account holder  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  Loan.Disbursement(asPayment).PaymentPartyRole(asCreditorRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EteNycTGEeChad0JzLk7QA_-591715083)  */
  payeeReference: Option[String],
  /* `status: Registered` bian-reference:  Loan.Disbursement(asPayment).PaymentPartyRole(asCreditorRole)(asPaymentPartyRole).CashAccount iso-link-1:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EvtpdMTGEeChad0JzLk7QA_-1076538618/elements/_EvtpdsTGEeChad0JzLk7QA_1151666800) `status: Provisionally Registered` bian-reference:  Loan.LoanAccount `status: Registered` bian-reference:  Loan.LoanAccount iso-link-2:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E4gZEcTGEeChad0JzLk7QA_2010102988) general-info: payee account  */
  payeeProductInstanceReference: Option[String],
  /* `status: Registered` bian-reference:  Loan.Disbursement(asPayment).PaymentPartyRole(asCreditorAgentRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EteNyMTGEeChad0JzLk7QA_-246206935)  */
  payeeBankReference: Option[String],
  amount: Option[CurrencyAndAmount],
  currency: Option[CurrencyCode],
  valueDate: Option[ISODateTime]
) extends ApiModel


