/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ConsumerLoanWithdrawalWithId (
  /* `status: Registered` bian-reference:  Loan.LoanAccount(asAccount).Identification iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E1rHgsTGEeChad0JzLk7QA_-1068889728/elements/_E1rHhcTGEeChad0JzLk7QA_-755813725) general-info: loan account number  */
  productInstanceReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  withdrawlInstructionReference: Option[String],
  /* `status: Registered` bian-reference:  LoanAgreement.TradePartyRole(asBorrower) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_t-Si4N1CEeGAp99n2TKigg_-919072642) general-info: loan account holder  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  Loan.Withdrawal(asPayment).PaymentPartyRole(asCreditorRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EteNycTGEeChad0JzLk7QA_-591715083)  */
  payeeReference: Option[String],
  /* `status: Registered` bian-reference:  Loan.Withdrawal(asPayment).PaymentPartyRole(asCreditorRole)(asPaymentPartyRole).CashAccount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EvtpdMTGEeChad0JzLk7QA_-1076538618/elements/_EvtpdsTGEeChad0JzLk7QA_1151666800) general-info: payee account  */
  payeeProductInstanceReference: Option[String],
  /* `status: Registered` bian-reference:  Loan.Withdrawal(asPayment).PaymentPartyRole(asCreditorAgentRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EteNyMTGEeChad0JzLk7QA_-246206935)  */
  payeeBankReference: Option[String],
  amount: Option[CurrencyAndAmount],
  currency: Option[CurrencyCode],
  valueDate: Option[ISODateTime]
) extends ApiModel


