/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ConsumerLoanBase (
  /* `status: Registered` iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633) bian-reference: Loan.Agreement.TradePartyRole(as Borrower)(as Role).Player(as Party) general-info: loan account holder  */
  customerReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  customerAgreementReference: Option[String],
  /* `status: Provisionally Registered` bian-reference: LoanAgreement.TradePartyRole(as Borrower)(as Role).Player(as Party).AccountableParty  */
  partyReference: Option[String],
  /* `status: Provisionally Registered` bian-reference: Loan.CreditCheck  */
  customerCreditAssessmentReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  insuranceReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  delinquencyCollectionReference: Option[String],
  /* `status: Registered` bian-reference:  LoanAgreement.TradePartyRole(asLender)(asRole).Player(asParty).Location iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_z2I6YGx5EeKmZJ0Ago--9g_239738909) general-info: for processing/logistics  */
  bankBranchLocationReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier general-info: for booking  */
  bankAccountingUnitReference: Option[String],
  /* `status: Registered` bian-reference:  LoanAgreement.CollateralPartyRole(asGiverRole) iso-link-1:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EuN0ocTGEeChad0JzLk7QA_1159142715) `status: Registered` bian-reference:  LoanAgreement.CollateralPartyRole(asTakerRole) iso-link-2:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ex8eFcTGEeChad0JzLk7QA_-1939123823) `status: Registered` bian-reference:  LoanAgreement.GuaranteePartyRole(asGuaranteeBeneficiary) iso-link-3:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EuN0p8TGEeChad0JzLk7QA_-1821987913) `status: Registered` bian-reference:  LoanAgreement.GuaranteePartyRole(asGuarantorRole) iso-link-4:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EuN0psTGEeChad0JzLk7QA_150894546) `status: Registered` bian-reference:  LoanAgreement.LoanProduct.Loan(asAsset).Trade.TradePartyRole(asBorrower) iso-link-5:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_t-Si4N1CEeGAp99n2TKigg_-919072642) `status: Registered` bian-reference:  LoanAgreement.LoanProduct.Loan(asAsset).Trade.TradePartyRole(asLender) iso-link-6:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_t-Si4d1CEeGAp99n2TKigg_-1009340668) general-info: guarantor/cosigner  */
  involvedPartyReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  involvedPartyObligationEntitlement: Option[String],
  /* `status: Provisionally Registered` bian-reference: Loan.LoanType general-info: term, revolving, evergreen  */
  loanType: Option[String],
  /* `status: Registered` bian-reference:  Loan(asAsset).InvestmentAmount iso-link-1:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FPv0acTGEeChad0JzLk7QA_-150026816/elements/_FepzGcTGEeChad0JzLk7QA_298530288) `status: Registered` bian-reference:  Loan.PrincipalAmount iso-link-2:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_mw1ysHJTEeWwf47VrwMaTQ/elements/_QLjLYHJUEeWwf47VrwMaTQ)  */
  loanAmount: Option[Double],
  /* `status: Registered` bian-reference:  Loan(asAsset).InvestmentAmount iso-link-1:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FPv0acTGEeChad0JzLk7QA_-150026816/elements/_FepzGcTGEeChad0JzLk7QA_298530288) `status: Registered` bian-reference:  Loan(asDebt).PaymentCurrency iso-link-2:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ff_P1MTGEeChad0JzLk7QA_-1514166912/elements/_X0hLUKRMEeO1ke9HGqKZhg) `status: Registered` bian-reference:  Loan.PrincipalAmount iso-link-3:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_mw1ysHJTEeWwf47VrwMaTQ/elements/_QLjLYHJUEeWwf47VrwMaTQ)  */
  loanCurrency: Option[String],
  /* `status: Registered` bian-reference:  Loan(asDebt).NextInterest.VariableInterest.VariableRateChangeFrequency iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fd5lKcTGEeChad0JzLk7QA_-958104524/elements/_FeNHIMTGEeChad0JzLk7QA_-12422289)  */
  loanRateType: Option[String],
  /* `status: Registered` bian-reference:  Loan(asDebt).NextInterest.VariableInterest iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FXWRMsTGEeChad0JzLk7QA_-398781879/elements/_FXgCNMTGEeChad0JzLk7QA_-129916673)  */
  loanApplicableRate: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  repaymentType: Option[String],
  /* `status: Registered` bian-reference:  Loan.InterestPaymentsSchedule.PaymentPeriod iso-link-1:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_jF5agJh7EeOUgsYi4EbJBw/elements/_AcedgZh9EeORjJTqwAvaiQ) `status: Registered` bian-reference:  Loan.PrincipalPaymentsSchedule.PaymentPeriod iso-link-2:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_jF5agJh7EeOUgsYi4EbJBw/elements/_AcedgZh9EeORjJTqwAvaiQ)  */
  loanRepaymentSchedule: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  interestType: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  interestAccrualMethod: Option[String],
  /* `status: Registered` bian-reference:  Loan.InterestPaymentsSchedule.RelatedPaymentObligation.PaymentOffset iso-link-1:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FDPCYMTGEeChad0JzLk7QA_-1131921749/elements/_FDPCacTGEeChad0JzLk7QA_-72272631) `status: Registered` bian-reference:  Loan.PrincipalPaymentsSchedule.RelatedPaymentObligation.PaymentOffset iso-link-2:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FDPCYMTGEeChad0JzLk7QA_-1131921749/elements/_FDPCacTGEeChad0JzLk7QA_-72272632)  */
  stagedRepaymentStatement: Option[String],
  /* `status: Registered` bian-reference:  Loan.PrincipalAmount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_mw1ysHJTEeWwf47VrwMaTQ/elements/_QLjLYHJUEeWwf47VrwMaTQ)  */
  loanOutstandingBalance: Option[String],
  loanOriginationDate: Option[ISODateTime],
  loanMaturityDate: Option[ISODateTime],
  /* `status: Registered` bian-reference:  LoanAgreement(asMasterAgreement).CollateralAgreement.Collateral iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E6vNtsTGEeChad0JzLk7QA_393174175/elements/_lrcFQC1hEeGp2Zpvgj9Dtw_-638405304)  */
  collateralReference: Option[String],
  /* `status: Registered` bian-reference:  LoanAgreement(asMasterAgreement).CollateralAgreement.Collateral.Valuation iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FLlGEcTGEeChad0JzLk7QA_1826831344/elements/_AAYPOmIjEeGD28DQaMef-g) general-info: value applied  */
  collateralAllocation: Option[String],
  /* `status: Provisionally Registered` bian-reference: Loan.LoanProduct(as Product).AvailableOption `status: Provisionally Registered` bian-reference: Loan.SelectedOption  */
  configurationOptions: Option[String],
  /* `status: Registered` iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FEHzNMTGEeChad0JzLk7QA_-1382123937/elements/_FEHzNcTGEeChad0JzLk7QA_-1792766550) bian-reference: LoanAgreement.TradePartyRole(as Borrower).Player(as Party).Identification.TaxIdentificationNumber general-info: Tax-Id  */
  taxReference: Option[String],
  /* `status: Registered` bian-reference:  Loan(asDebt).PrePaymentSpeed iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ff_P1MTGEeChad0JzLk7QA_-1514166912/elements/_Fg4nt8TGEeChad0JzLk7QA_742037711) `status: Provisionally Registered` bian-reference:  Loan.Limit general-info: allowed payments/withdrawals  */
  loanAccessTerms: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  customerCommentary: Option[String]
) extends ApiModel


