/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ConsumerLoanMaintenanceWithId (
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier general-info: loan account number  */
  productInstanceReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text general-info: tasks, e.g. reporting and loan review actions  */
  productFulfillmentSchedule: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code general-info: e.g tax, regulatory, accounting  */
  reportType: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  */
  loanTaxReport: Option[Any],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  loanFeeType: Option[String],
  /* `status: Provisionally Registered` bian-reference:  Loan.LoanAccount(asAccount).Adjustment(asCharges) `status: Registered` bian-reference:  Loan.LoanAccount(asAccount).Adjustment(asCharges) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FMBK9sTGEeChad0JzLk7QA_-398781908) general-info: as booked against loan account  */
  loanFees: Option[String],
  /* `status: Provisionally Registered` bian-reference:  Loan.LoanAccount(asAccount).Adjustment(asPenalty) `status: Registered` bian-reference:  Loan.LoanAccount(asAccount).Adjustment(asPenalty) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_eEiTMHRkEeKIFpWttHerUA_-261419352) general-info: as booked against loan account  */
  penalties: Option[String],
  /* `status: Registered` bian-reference:  LoanAgreement(asMasterAgreement).GovernedContract(asCollateralAgreement).Collateral.Valuation iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FLlGEcTGEeChad0JzLk7QA_1826831344/elements/_AAYPOmIjEeGD28DQaMef-g) general-info: value confirmed as of date  */
  collateralValuation: Option[String]
) extends ApiModel


