/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CurrentAccountBase (
  /* `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountOwnerRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EysE9cTGEeChad0JzLk7QA_-200588046)  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountServicerRole)(asRole).Player(asParty).Location iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_z2I6YGx5EeKmZJ0Ago--9g_239738909) general-info: for booking purposes  */
  bankBranchLocationReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  dateType: Option[String],
  date: Option[ISODateTime],
  /* `status: Registered` bian-reference:  CashAccountContract(asAgreement).RoleInAgreement(asGuaranteePartyRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_G7hIgGcwEeOYlMxMjJVrrQ) general-info: e.g. guarantor/co-signer  */
  involvedPartyReference: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CashAccountContract(asAgreement).Obligation `status: Registered` bian-reference:  CashAccountContract(asAgreement).Obligation iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FL4BCcTGEeChad0JzLk7QA_-1814618756)  */
  involvedPartyObligationEntitlement: Option[String],
  /* `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountOwnerRole)(asRole).Player(asOrganization).OrganisationIdentification.LEI iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FEHzNMTGEeChad0JzLk7QA_-1382123937/elements/_yagFILl5EeOpCN0IL2Swqw) `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountOwnerRole)(asRole).Player(asPerson).PersonIdentification.TaxIdentificationNumber iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FEHzNMTGEeChad0JzLk7QA_-1382123937/elements/_FEHzNcTGEeChad0JzLk7QA_-1792766550)  */
  partyReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.CashAccountType iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E4gZEcTGEeChad0JzLk7QA_2010102987/elements/_E4gZE8TGEeChad0JzLk7QA_1025780411)  */
  accountType: Option[String],
  accountCurrency: Option[CurrencyCode],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  accountLimitType: Option[String],
  /* `status: Registered` bian-reference:  (asDebitCreditFacility).Limit iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FAsrxsTGEeChad0JzLk7QA_-351673533/elements/_FAsryMTGEeChad0JzLk7QA_-1033977641)  */
  accountLimit: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CashAccount(asAccount).AccountRestriction.RestrictionDescription `status: Registered` bian-reference:  CashAccount(asAccount).AccountRestriction.RestrictionType iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E10RdcTGEeChad0JzLk7QA_-917313471/elements/_E10RdsTGEeChad0JzLk7QA_-1031152537)  */
  allowedAccess: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  optionType: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  option: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.CashEntry.Amount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FAi6wsTGEeChad0JzLk7QA_-1438285571/elements/_FAi6w8TGEeChad0JzLk7QA_1158844272) general-info: Tax-Id  */
  taxReference: Option[String]
) extends ApiModel


