/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CustomerAssociationBaseWithIdAndRoot (
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  customerReferenceDataDirectoryEntryReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  associationsDirectoryEntryReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager(asRole).Player(asPerson).EmployerIdentificationNumber iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7VDkcTGEeChad0JzLk7QA_-2076942625/elements/_E7VDlcTGEeChad0JzLk7QA_-912215424)  */
  employeeReference: Option[String],
  /* `status: Provisionally Registered`  bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).PartyRelationship.PartyRelationshipType  general-info: familial or corporate  */
  associateType: Option[String],
  /* `status: Provisionally Registered`  bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).PartyRelationship  */
  associateReference: Option[String],
  /* `status: Provisionally Registered`  bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).PartyRelationship.Agreement  */
  associateObligationDependencyDescription: Option[String],
  /* `status: Provisionally Registered`  bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).PartyRelationship.ValidityPeriod  */
  associationValidFromTo: Option[String],
  /* `status: Provisionally Registered`  bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).PartyRelationship.RelationshipAgreement.Product  general-info: association tied to bank product/service  */
  productInstanceReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player.Role(asAccountPartyRole).Account.A iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EuN0p8TGEeChad0JzLk7QA_-1821987913) general-info: list  */
  preferredBeneficiary: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).PowerOfAttorney iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/___CLVmIiEeGD28DQaMef-g)  */
  proxyRepresentativePowerOfAttorneyReference: Option[String]
) extends ApiModel


