/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DemographicBase (
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).Household iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_0Lx2wLZeEeOpCN0IL2Swqw) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).PersonProfile iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_q6wNUB9uEeO3iLV2voicmw)  */
  socioEconomicClassification: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).Ethnicity `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).Religion  */
  ethnicityReligion: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty)(asPerson).PersonProfile.SalaryRange iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_ZUHGwB9uEeO3iLV2voicmw/elements/_FNg_wMTGEeChad0JzLk7QA_666058283) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty)(asPerson).Profession iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_FNXOx8TGEeChad0JzLk7QA_-382216715) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).EmployerIdentificationNumber iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7VDkcTGEeChad0JzLk7QA_-2076942625/elements/_E7VDlcTGEeChad0JzLk7QA_-912215424) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.(asRole).Player(asParty)(asPerson).PersonProfile.EmploymentTerminationIndicator iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_ZUHGwB9uEeO3iLV2voicmw/elements/_SfbZ0CHSEeO3iLV2voicmw) general-info: employer and position  */
  employment: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text general-info: employer, job position, salary  */
  employmentHistory: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.(asRole).Player(asPerson).EducationLevel  general-info: academic institutions, duration, certifications  */
  educationHistory: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.CustomerMasterAgreement(asAgreement).TermsAndConditions `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.CustomerMasterAgreement.TermsAndConditions  */
  servicingConstraints: Option[String]
) extends ApiModel


