/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DepositBase (
  /* `status: Registered` iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EysE9cTGEeChad0JzLk7QA_-200588046) general-info: customer  */
  payeeReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount(asAccount).Identification iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E1rHgsTGEeChad0JzLk7QA_-1068889728/elements/_E1rHhcTGEeChad0JzLk7QA_-755813725) general-info: customer account reference  */
  payeeProductInstaceReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountServicerRole) iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ey118MTGEeChad0JzLk7QA_1536519000)  */
  payeeBankReference: Option[String],
  amount: Option[CurrencyAndAmount],
  currency: Option[CurrencyCode],
  valueDate: Option[ISODateTime]
) extends ApiModel


