/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DirectDebitBase (
  /* `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).MandateIdentification iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FctSUcTGEeChad0JzLk7QA_1037644309/elements/_C-4qwERwEeKKnZkMwum2NA_253647161) general-info: payee  */
  directDebitMandateReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).Description iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E2tpUMTGEeChad0JzLk7QA_1799405832/elements/_E2tpUcTGEeChad0JzLk7QA_700879817) general-info: e.g. for compliance reporting  */
  directDebitPurpose: Option[String],
  /* `status: Registered` bian-reference:  CashAccountContract(asAccount).AccountAuthorisation(asDirectDebitMandate).CollectionAmount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FCCvlMTGEeChad0JzLk7QA_-1453577952/elements/_FCCvl8TGEeChad0JzLk7QA_1129069978) `status: Registered` bian-reference:  CashAccountContract(asAccount).AccountAuthorisation(asDirectDebitMandate).MaximumAmount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FCCvlMTGEeChad0JzLk7QA_-1453577952/elements/_FCCvmcTGEeChad0JzLk7QA_-960859698) `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).FinalCollectionDate iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FCCvlMTGEeChad0JzLk7QA_-1453577952/elements/_FCCvlsTGEeChad0JzLk7QA_1037644588) `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).FirstCollectionDate iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FCCvlMTGEeChad0JzLk7QA_-1453577952/elements/_FCCvlcTGEeChad0JzLk7QA_1037644587) `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).Frequency iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FCCvlMTGEeChad0JzLk7QA_-1453577952/elements/_FCCvmMTGEeChad0JzLk7QA_1037644589) general-info: amount/limits/schedule  */
  directDebitServiceConfiguration: Option[String],
  /* `status: Registered` iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNg_x8TGEeChad0JzLk7QA_908383601/elements/_FNqJtcTGEeChad0JzLk7QA_-1846259904) general-info: for booking purposes  */
  bankBranchLocationReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).MandatePartyRole(asMandateHolder) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EvHMh8TGEeChad0JzLk7QA_1036121131)  */
  payeeReference: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate)(asMandate).CreditorAccount `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate)(asMandate).CreditorAccount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E4gZEcTGEeChad0JzLk7QA_2010102987)  */
  payeeProductInstanceReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccountContract(asAccountContract).AccountAuthorisation(asDirectDebitMandate).CreditorAccount(asAccount).AccountPartyRole(asAccountServicerRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ey118MTGEeChad0JzLk7QA_1536519000)  */
  payeeBankReference: Option[String],
  amount: Option[CurrencyAndAmount],
  currency: Option[CurrencyCode]
) extends ApiModel


