/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PaymentBase (
  /* `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountOwnerRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EysE9cTGEeChad0JzLk7QA_-200588046)  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.Payment.PartyRole(asCreditorRole) iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EteNycTGEeChad0JzLk7QA_-591715083)  */
  payeeReference: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CashAccount.Payment.PartyRole(asCreditorRole)(asPaymentPartyRole).CashAccount iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EvtpdMTGEeChad0JzLk7QA_-1076538618/elements/_EvtpdsTGEeChad0JzLk7QA_1151666800) general-info: account number  */
  payeeProductInstanceReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.Payment.PartyRole(asCreditorAgentRole) iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EteNyMTGEeChad0JzLk7QA_-246206935)  */
  payeeBankReference: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  accountLimitType: Option[String],
  accountLimit: Option[CurrencyAndAmount],
  amount: Option[CurrencyAndAmount],
  currency: Option[CurrencyCode],
  valueDate: Option[ISODateTime],
  /* `status: Registered` bian-reference:  CashAccount.Payment.PaymentInstrument iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FCL5hcTGEeChad0JzLk7QA_1746210980/elements/_FAi6ycTGEeChad0JzLk7QA_1746210990)  */
  paymentMechanism: Option[String]
) extends ApiModel


