/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ReferenceBase (
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty) iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EwTfUMTGEeChad0JzLk7QA_-1978180945/elements/_EwTfUcTGEeChad0JzLk7QA_434950303) general-info: consumer  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).Identification iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_FNqJucTGEeChad0JzLk7QA_1357540588)  */
  customerLegalEntityReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).Identification.PartyName iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FEHzNMTGEeChad0JzLk7QA_-1382123937/elements/_FEHzN8TGEeChad0JzLk7QA_1608854558)  */
  customerNameSalutation: Option[String],
  /* `status: Registered` iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_wetlYA93EeGeV5vP7Mvdig_1485186470) general-info: social security number  */
  governmentIssuedIdentityReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).PersonIdentification iso-link: [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7VDkcTGEeChad0JzLk7QA_-2076942625/elements/_E7VDksTGEeChad0JzLk7QA_-855295891) general-info: driving license/passport details  */
  governmentIssuedDocumentDetails: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).ResidentialStatus iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_FNXOxsTGEeChad0JzLk7QA_-1496564084)  */
  residencyStatus: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).BirthDate iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_FNXOwcTGEeChad0JzLk7QA_-1677946145)  */
  dateOfBirth: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty)(asPerson).Nationality iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_FNXOxMTGEeChad0JzLk7QA_-1677946132) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asPerson).PlaceOfBirth iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147/elements/_FNXOyMTGEeChad0JzLk7QA_-1037578805)  */
  nationality: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).Residence iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_FNz6sMTGEeChad0JzLk7QA_1111100108)  */
  residentialAddress: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).ContactPoint(asElectronicAddress) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_FEHzOMTGEeChad0JzLk7QA_-1894201405) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).ContactPoint(asElectronicAddress) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FQ8HM8TGEeChad0JzLk7QA_1582936206)  */
  emailAddress: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).ContactPoint(asPhoneAddress) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_FEHzOMTGEeChad0JzLk7QA_-1894201405) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).ContactPoint(asPhoneAddress) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNz6usTGEeChad0JzLk7QA_352593535)  */
  cellPhoneNumber: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).ContactPoint(asElectronicAddress).SocialNetworkAddress `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asParty).ContactPoint(asElectronicAddress).SocialNetworkAddress iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNqJt8TGEeChad0JzLk7QA_-1317971633/elements/_FEHzOMTGEeChad0JzLk7QA_-1894201405)  */
  socialNetworkContacts: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  */
  politicalExposureType: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Binary  */
  politicalExposureRecord: Option[Any],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asOrganisation) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EwTfUMTGEeChad0JzLk7QA_-1978180945/elements/_EwTfUcTGEeChad0JzLk7QA_434950303) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asOrganisation) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNg_x8TGEeChad0JzLk7QA_908383601) general-info: Company  */
  corporateCustomerReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asOrganisation).OrganisationIdentification(asPartyIdentificationInformation).LEI iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FEHzNMTGEeChad0JzLk7QA_-1382123937/elements/_yagFILl5EeOpCN0IL2Swqw)  */
  corporateCustomerLegalEntityReference: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asOrganisation).PlaceOfOperation iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNg_x8TGEeChad0JzLk7QA_908383601/elements/_FNqJtcTGEeChad0JzLk7QA_-1846259904) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).Player(asOrganisation).PlaceOfRegistration iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNg_x8TGEeChad0JzLk7QA_908383601/elements/_FNqJtMTGEeChad0JzLk7QA_-847083437)  */
  corporateAddress: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EwKVZ8TGEeChad0JzLk7QA_-1034255710)  */
  companyOfficerRole: Option[String],
  /* `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager(asRole).Player(asPerson) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EwTfUMTGEeChad0JzLk7QA_-1978180945/elements/_EwTfUcTGEeChad0JzLk7QA_434950303) `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer.RelationshipManager(asRole).Player(asPerson) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNXOwMTGEeChad0JzLk7QA_-1677946147)  */
  companyOfficerReference: Option[String],
  /* `status: Provisionally Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).ApplicablePeriod.FromDateTime `status: Registered` bian-reference:  CustomerRegistryEntry.RegisteredCustomer(asRole).ApplicablePeriod.FromDateTime iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FJ8HVcTGEeChad0JzLk7QA_726404707)  */
  customerSinceDate: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Binary  */
  customerReferenceRecord: Option[Any]
) extends ApiModel


