/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ReferenceBaseUpdateRequest (
  customerNameSalutation: Option[String],
  governmentIssuedIdentityReference: Option[String],
  governmentIssuedDocumentDetails: Option[String],
  residencyStatus: Option[String],
  dateOfBirth: Option[String],
  nationality: Option[String],
  residentialAddress: Option[String],
  emailAddress: Option[String],
  cellPhoneNumber: Option[String],
  socialNetworkContacts: Option[String],
  politicalExposureType: Option[String],
  politicalExposureRecord: Option[Any],
  corporateCustomerReference: Option[String],
  corporateAddress: Option[String],
  companyOfficerRole: Option[String],
  companyOfficerReference: Option[String],
  customerSinceDate: Option[String],
  customerReferenceRecord: Option[Any]
) extends ApiModel


