/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class StandingOrderBaseWithIdAndRoot (
  /* `status: Registered` bian-reference:  CashAccount.RelatedCreditStandingOrder.EventDescription iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7CIosTGEeChad0JzLk7QA_1664636213/elements/_E7CIo8TGEeChad0JzLk7QA_-1879461400) `status: Registered` bian-reference:  CashAccount.RelatedDebitStandingOrder.EventDescription iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7CIosTGEeChad0JzLk7QA_1664636213/elements/_E7CIo8TGEeChad0JzLk7QA_-1879461400)  */
  standingOrderPurpose: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.RelatedCreditStandingOrder.CreditAccount(asAccount).AccountOwnerRole iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EysE9cTGEeChad0JzLk7QA_-200588046) `status: Registered` bian-reference:  CashAccount.RelatedDebitStandingOrder.CreditAccount(asAccount).AccountOwnerRole iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EysE9cTGEeChad0JzLk7QA_-200588046)  */
  payeeReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.RelatedCreditStandingOrder.CreditAccount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7CIosTGEeChad0JzLk7QA_1664636213/elements/_DK7EY7ShEeGXa-y3CFzLMQ_463118596) `status: Registered` bian-reference:  CashAccount.RelatedDebitStandingOrder.CreditAccount iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7CIosTGEeChad0JzLk7QA_1664636213/elements/_DK7EY7ShEeGXa-y3CFzLMQ_463118596) general-info: customer account reference  */
  payeeProductInstanceReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount.RelatedCreditStandingOrder.CreditAccount(asAccount).AccountServicerRole iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ey118MTGEeChad0JzLk7QA_1536519000) `status: Registered` bian-reference:  CashAccount.RelatedDebitStandingOrder.CreditAccount(asAccount).AccountServicerRole iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Ey118MTGEeChad0JzLk7QA_1536519000)  */
  payeeBankReference: Option[String],
  amount: Option[CurrencyAndAmount],
  currency: Option[CurrencyCode],
  /* `status: Registered` bian-reference:  CashAccount.RelatedCreditStandingOrder.Day iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7CIosTGEeChad0JzLk7QA_1664636213/elements/_E7CIpMTGEeChad0JzLk7QA_-1145087031) `status: Registered` bian-reference:  CashAccount.RelatedDebitStandingOrder.Frequency iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E7CIosTGEeChad0JzLk7QA_1664636213/elements/_E7CIqcTGEeChad0JzLk7QA_-1544240334)  */
  paymentSchedule: Option[String],
  /* `status: Not Mapped` core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  */
  standingOrderFacilityReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount(asAccount).AccountPartyRole(asAccountOwnerRole) iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_EysE9cTGEeChad0JzLk7QA_-200588046)  */
  customerReference: Option[String],
  /* `status: Registered` bian-reference:  CashAccount(asAccount).Identification iso-link:  [click-here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E1rHgsTGEeChad0JzLk7QA_-1068889728/elements/_E1rHhcTGEeChad0JzLk7QA_-755813725) general-info: account number  */
  productInstanceReference: Option[String]
) extends ApiModel


